{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Whole Cell Patch Clamp Recording Setup: Theory and Operation\n",
    "References: \n",
    "1. Multiclamp 700B User manual\n",
    "2. Axon Guide V Ed\n",
    "3. Single Channel Recording, Sakmann and Neher, 1995"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Whole Cell Patch Clamp Steps:\n",
    "\n",
    "### A. Electrode in bath:\n",
    "VC\n",
    "Pipette offset button: should cause the membrane current or holding current to become zero.\n",
    "Seal test: A 10mV pulse is generated to determine the resistance. In the bath, it should come out to be equal to the pipette resistance (few MΩ)\n",
    "\n",
    "CC\n",
    "Pipette offset: Pressing the pipette offset button should cause the pipette offset to become zero.\n",
    "Tuning: Similar to seal test in VC. Injected a 1 nA pulse and measures the Vp to give resistance value.\n",
    "\n",
    "### B. Giga seal: \n",
    "Transients appear and Rt ~ 1 GΩ, therefore, stead state current is very low (< 10pA for a 10mV pulse)\n",
    "\n",
    "Large amplitude transients appear at the start and end of the pulses. These are due to capacitances of patch electrode. These are bad as they can saturate the amplifier. There is a fast component and a slow component of this capacitance. These can be removed with Cp fast and Cp slow controls (Either the Auto button or by manually changing C and tau values).\n",
    "Cp fast: ~ 5 pF, 1 us\n",
    "Cp slow: ?\n",
    "After compensation, the transients should disapper.\n",
    "\n",
    "### C. Whole cell:\n",
    "VC\n",
    "The steady state current, for a usual neuron will be around 100 pA for a 10mV pulse. This is the input resistance of the whole cell (~100 MΩ).\n",
    "\n",
    "As soon as the seal is broken, the capacitance of the whole cell comes into the circuit and new transients appear. These transients are much slower than the Cp fast and Cp slow transients that we compensated before breaking the seal. The capacitance of the cell is usually more than 30 pF and upto 200 pF depending on the branching.\n",
    "\n",
    "These slow transients depend on the electrode resistance (now access resistance Ra) and cell capacitance (Cm). \n",
    "We should cancel these slow transients also, for the following reasons:\n",
    "1. They may saturate the amplifier.\n",
    "2. This cancellation is required for the proper series resistance compensation.\n",
    "\n",
    "This can be done in the \"Whole Cell\" section of VC tab. Auto and manual, both modes can be tried.\n",
    "\n",
    "Note: If a fast transient reappears after whole cell capacitance compensation, that can be removed by Cp fast auto.\n",
    "\n",
    "Note: Leak subtraction and Output zero sections are to remove the step currents due to voltage commands. Leak subtraction control works by subtracting a scaled version of the command voltage from the step current responses until the step current response becomes zero. This scaling would always be approximately equal to the input resistance of the cell. Output zero works to eliminate the offsets by applying a high pass filter. They are not recommended in whole cell recordings as there can be currents dependent on voltage of the cell.\n",
    "\n",
    "Series Resistance Compensation:\n",
    "Even after the elimination of the Cp fast, Cp slow, and Cm, one cn observe that the current response to the voltage step rises slowly (~1 ms). This is due to the series (aka access) resistance (Rs or Ra). The art of Rs compensation is to choose a combination of Bandwidth, Prediction and Correction that provides maximal compensation without oscillation.\n",
    "\n",
    "CC\n",
    "In current clamp, Cm and Rs cause slow rise of membrane potential upon injection of a current step. The Rs is in series with Rm and therefore even before the Vm starts charging, an ohmic potential falls onto the Rs. This looks like a voltage step. To remove this in current clamp, bridge balance control is used. The amplifier subtracts a scaled version of command current from the measured Vm. This scaling factor is due to Rs and therefore will be approximately equal to it. Auto or manual both modes can be used.\n",
    "\n",
    "Another factor is the capacitance of the electrode (Cp) that can cause errors. This can be removed by pipette capacitance neutralization. Over compensation can cause oscillations and therefore, pipette capacitance neutralization value should be carefully and gradually changed. (~ < 3 pF)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Pressure in the electrode:\n",
    "\n",
    "- Bath:   30 mbar,\n",
    "- Before entering the tissue: 80 to 120 mbar,\n",
    "- After entering the tissue:  30 to 50 mbar,\n",
    "- Close to the cell:         -50 to -100 mbar,\n",
    "- close to Gigaohm seal:      0 mbar,\n",
    "- to break the seal:          80 mbar, 0.5s pulses"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Notes\n",
    "\n",
    "* Fast capacitive spikes (cp fast) recorded are due to pipette and the enclosed membrane patch. They should be neurtralized before breaking into the cell.\n",
    "\n",
    "* Gain settings should be selected for best possible resolution without hitting the saturation limit.\n",
    "    Feedback register (Rf) = 500 MΩ\n",
    "    Voltage clamp: Gain = 10 => 5 V/nA.     Range = +/- 2 nA,  Resolution = 2nA/16bits   = 0.03 pA/bit\n",
    "    Current clamp: Gain = 10 => 100 mV/mV.  Range = +/- 100mV, Resolution = 100mV/16bits = 1.52 µV/bit\n",
    "      \n",
    "* Breaking the patch:\n",
    "    + Access to the cell can be seen as sudden increase in capacitive transients and, \n",
    "    + depending on the input resistance of the cell, a shift in the current level or background noise.\n",
    "    + Smaller access resistance => larger capacitive transients, but shorted duration\n",
    "    + High levels of EGTA (10mM) buffers Ca+2 ions and prevents spontaneous increase in access resistance and resealing.\n",
    "\n",
    "* Capacitive trasient cancellation:\n",
    "    + If the Cp fast was neutralized before breaking into the cell, then all the new capacitance will be due to the cell capacitance (Cm).\n",
    "    + If cells have more complex geometry, there will be multiple capcitive time constants and neutralization will never be perfect or complete.  \n",
    "       \n",
    "* Series resistance compensation:\n",
    "    +"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Glossary\n",
    "\n",
    "1. Bath resistance (Rb) is additive to the Rm and therefore is indistinguishable from Rm and acts as an access resistance component. It is usually very low (~ 1 kΩ) but to keep it lower, larger surface area reference Ag/AgCl should be used.\n",
    "For a passing of current of ~ 1 nA, it would cause a potential drop of 1 µV.\n",
    "\n",
    "2. Bridge Balance: Used to subtract voltage drop across pipette resistance (Rp) in current clamp. When a current is passed through the pipette into the cell, the cell Vm changes. This Vm is read at the end of the pipette as Vp. The passing current causes a voltage drop across the pipette and cause a voltage drop of Vdrop = IxRp. This unwanted voltage drop is added to the recorded potential. Bridge balance removes this drop so that only Vm is recorded.\n",
    "\n",
    "    When done in the bath: The bridge balance gives the value of resistance of the pipette.\n",
    "    \n",
    "    When done is the cell: Pipette capacitance neutralization should be set the same time as the bridge balance. The pipette resistance and capacitance can change after the whole cell is established, so it is a good idea to monitor the bridge balance and pipette capacitance regularly while in the cell.\n",
    "\n",
    "3. Capacitance compensation in Voltage clamp\n",
    "\n",
    "Electrode:  Cp fast component, represented as capacitance at headstage input and,\n",
    "            Cp slow component, represented as a capacitor parallel to Rs\n",
    "            This is done by supplying the required fast current through a capacitor (C1) instead of letting it pass through Rf.\n",
    "\n",
    "Cell     :  Whole cell capacitance (Cm)\n",
    "            The time constant of whole cell capacitance transient is determined by the product of Cm and series resistance (Rs). If this becomes large, the transients can last longer causing distortion in cellular currents of interest. It is therefore, desirable to compensate for the cell capacitance. Also, whole cell capacitance compensation is required to compensate the series resistance.\n",
    "            Our measure of cellular currents comes via feedback resistors. Whole cell capacitive compensation works by offloading the task of charging the cellular capacitor from Rf to a fast capacitor (C2).\n",
    "\n",
    "The capacitance and resistance values displayed by the whole cell compensation section in multiclamp commander give estimates of Cm and Rs respectively. These estimates are only good if Rs << Rm.\n",
    "\n",
    "4. Capacitance Neutralization in Current Clamp\n",
    "\n",
    "In current clamp, the pipette capacitance is needed to be neutralized. This is easier if bridge balance is adjusted already to remove the pipette resistance. The option for pipette capacitance neutralization is in the current clamp tab. It should be gradually increased to avoid oscillations. (usual value ~ 3pF)\n",
    "\n",
    "5. External command sensitivity\n",
    "For Rf = 500MΩ\n",
    "VC: ECS =  20 mV/V\n",
    "CC: ECS = 400 pA/V\n",
    "\n",
    "6. Feedback resistor (Rf)\n",
    "VC: Determines the gain of headstage. Larger Rf means less noise, but at the risk of saturation if there are going to be larger currents in the cell. Rf of 500 MΩ is recommended for whole cell patching of neurons. I want to try 5GΩ. Since the amplifier can only create a maximum of 10 V step, this would mean that only upto 2 nA current can be passed if the Rf = 5GΩ.\n",
    "\n",
    "CC: Determines the maximal injectable current by the amplifier. Rf should be between 10xRin to 0.1xRin. For ex. for a hippocampal pyramidal cell (Rm = 150mΩ), the Rf can be between 15MΩ and 1500MΩ. Therefore, Rf = 500MΩ should be selected.\n",
    "Changing Rf in CC will also change the external command sensitivity.\n",
    "\n",
    "7. Grounding\n",
    "Grounding bus should be connected to the \"Signal Ground\" at the back of the MCC module.\n",
    "\n",
    "8. Headstage\n",
    "In VC\n",
    "Circuit is basically an I-V converter op-amp that converts current required to maintain Vp equal to Vcmd into voltage (Vo) that is measured. For single electrode voltage clamp\n",
    "\n",
    "\n",
    "Voltage Clamp:\n",
    "For single electrode VC, series resistance compensation is required. For the compensation to work, Rs should be lower than Rm. The voltage input to the op-amp is the voltage at the top of the pipette (Vp). \n",
    "\n",
    "    Vp = Vm + current induced voltage drop across the access resistance\n",
    "\n",
    "Access resistance (aka series resistance, Rs) = resistance due to pipette + cellular debris in the patch\n",
    "\n",
    "For large currents, the voltage drop on series resistance will be significant, thus causing insufficient voltage clamping, which will in turn cause wrong current injection to maintain the voltage clamp. Therefore, series resistance should be compensated. If Ra and Ra_eff are series resistance before and after compensation, then:\n",
    "\n",
    "    Vm  = Vcmd - Im * Ra_eff\n",
    "\n",
    "&   tau = [Ra_eff * Rm/ (Ra_eff + Rm)] * Cm\n",
    "\n",
    "if Rm >> Ra_eff\n",
    "\n",
    "    tau ≈ Ra_eff * Cm\n",
    "\n",
    "### Series resistance and Series resistance Compensation (SRC):\n",
    "Sources:\n",
    "- Pipette resistance\n",
    "- Intracellular organelles and debris stuck in the patch\n",
    "- Cellular debris that covers the cell membrane\n",
    "- Bath solution and bath reference (minor)\n",
    "\n",
    "Problems due to Rs\n",
    "- Steady state voltage errors: in steady state, a steady flow of current will cause a steady drop of voltage on Rs, with the direction of drop depending on direction of current.\n",
    "\n",
    "    Vm = Vcmd - Im * Rs\n",
    "\n",
    "- Dynamic voltage errors: following a step change in Vcmd, the Vm will charge to Vcmd with an exponential time course according to:\n",
    "\n",
    "    tau = Rs * Cm\n",
    "\n",
    "- Bandwidth errors: Rs and Cm together act like a low pass filter, with a -3dB cutoff given by:\n",
    "\n",
    "    f(-3dB) = 1/(2*pi*Rs*Cm)\n",
    "\n",
    "#### SRC = Correction + Prediction\n",
    "\n",
    "Correction: Done by positive feedback. The Vcmd is increased by a signal proportional to the measured current. This increased command compensates for potential drop on the series resistance. The compensation beyond  ~ 90% causes oscillations.\n",
    "\n",
    "Prediction: Done by supercharging, generally safer upto 95-98%"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Noise\n",
    "\n",
    "RMS  is better than P2P\n",
    "Sources:\n",
    "VC:\n",
    "    - High seal resistance -> low noise\n",
    "    - For larger cells, cellular noise dominates\n",
    "    - Low electrode capacitance --> low noise\n",
    "    - High electrode resistance  --> low noise, but it is better to have low resistance electrodes for having a better bandwidth\n",
    "    - High feedback resistor --> low noise\n",
    "    - Rs compensation increases noise\n",
    "CC:\n",
    "    - Low load resistance --> low noise\n",
    "    - Low capacitance --> low noise, but poor bandwidth\n",
    "    - Low Rf --> low noise, but Rf should be between 0.2 * Rm to 5 * Rm (due to range of capacitance neutralization circuit)\n",
    "    - Increasing pipette cap neutralization --> more noise\n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "efceb7404fb9811cf40b75e40bd8d8d061e2563981c73d0ff752e54aeb51c26e"
  },
  "kernelspec": {
   "display_name": "Python 3.7.9 64-bit ('venv-lab': venv)",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
